### ISSUE TITLE
Investigate approach to exclusively use managed host

### ISSUE THREAD

**Issue by sergioifg94** [Kuadrant/multi-cluster-traffic-controller#25]
## What

Currently, MCTC has the ability to set an autogenerated managed host for every rule in the Ingress that it reconciles. It does so by duplicating the rule and setting the host of the duplicated rule as an algorithmically generated host. For example, with `ZONE_ROOT_DOMAIN` being `mctc.io`, the spec would be reconciled from this:
```yaml
spec:
  rules:
    - host: example.custom.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo
                port:
                  number: 80
```
To this
```yaml
spec:
  rules:
    - host: example.custom.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo
                port:
                  number: 80
    - host: <autogenerated>.mctc.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo
                port:
                  number: 80
```

## Why

It is possible for there to be a scenario where a user wants to create an Ingress without passing a specific host, only expecting to use the autogenerated managed host. Previously, in the kcp supported controller, the empty string would be used for this scenario. However, in the new architecture, the Ingress is also subject to be reconciled by the Nginx Ingress Controller. This controller sets a validation on Ingresses that ensures the empty host is only used once across the cluster, which limits the usage of it

## How

Investigate alternative approaches to set rules that exclusively rely on the managed host without conflicting with the Ngnix controller.
